---
- name: crate a directory
  become: yes
  file:
    path: "{{ helm_dest }}"
    state: directory
    mode: 0755
  tags:
    - container
    - helm

- name: download helm binary
  become: yes
  unarchive:
    src: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "{{ helm_dest }}"
    remote_src: yes
    mode: 750
  tags:
    - container
    - helm

- name: change ownership of helm directory
  become: yes
  file:
    path: "{{ helm_dest }}"
    state: directory
    recurse: yes
    owner: "{{ ansible_user }}"
    group: "{{ unix_group }}"
    mode: 750
  tags:
    - container
    - helm

- name: create a symbolic link
  become: yes
  file:
    src: "{{ helm_dest }}/linux-amd64/helm"
    dest: /usr/local/bin/helm
    owner: "{{ ansible_user }}"
    group: "{{ unix_group }}"
    state: link
  tags:
    - container
    - helm
