- name: check if config directory exists
  stat:
    path: "{{ home_directory }}/configs"
  register: dot_files_directory

- name: clone dot-files
  git:
    repo: "https://github.com/orltom/linux-user-configs"
    dest: "{{ home_directory }}/configs"
    refspec: '+refs/pull/*:refs/heads/*'
    version: master
  when: not dot_files_directory.stat.exists
  tags:
    - system

- name: add config links
  file:
    src: "{{ home_directory }}/configs/{{ item }}"
    dest: "{{ home_directory }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  loop:
    - .vimrc
    - .bashrc
    - .zshrc
  tags:
    - system

- name: add user bin command links
  file:
    src: "{{ home_directory }}/configs/bin/{{ item }}"
    dest: "{{ home_directory }}/bin/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  loop:
    - gitlastcommit
    - gitupdatebranch
    - change-keyboard-layout
  tags:
    - system

- name: add .config programm links
  file:
    src: "{{ home_directory }}/configs/.config/{{ item }}"
    dest: "{{ home_directory }}/.config/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  loop:
    - i3
    - rofi
    - dunst
  tags:
    - system
