---
- name: Add Kubernetes APT repository
  become: yes
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    filename: kubernetes
    state: present
  tags:
    - container
    - kubernetes
    - kubectl

- name: Install kubectl system packages
  become: yes
  package:
    name: kubectl
    state: present
  tags:
    - container
    - kubernetes
    - kubectl
