- name: Add Spotify key
  apt_key:
    url:  https://download.spotify.com/debian/pubkey.gpg
    state: present

- name: register spotify apt repository
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    filename: spotify
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install spotify
  package:
    name: spotify-client
    update_cache: yes
    state: present