- name: install common packages
  package:
    name:
      - i3
      - rofi
      - dunst
      - compton
      - powerline
      - fonts-powerline
      - fonts-font-awesome
    state: present
  tags:
    - i3

- name: Install shell and extensions
  package:
    name:
      - zsh
      - fonts-powerline
      - fonts-font-awesome
    state: present
  tags:
    - system

- name: set ZSH as default terminal
  shell: chsh -s $(which zsh)
  tags:
    - system

- name: check if ohmyzsh directory exists
  stat:
    path: "/home/{{ ansible_user }}/.oh-my-zsh"
  register: ohmyzsh-directory

- name: clone omyzsh
  shell: git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
  when: ohmyzsh-directory.stat.exists == False
  tags:
    - system
