- name: install common packages
  package:
    name:
      - i3
      - gnome-terminal
      - gdm3
      - rofi
      - dunst
      - compton
      - powerline
      - fonts-powerline
      - fonts-font-awesome
    state: present
    become: yes
  tags:
    - i3

- name: Insatll bumblebee-status
  pip:
    name:
      - bumblebee-status
      - configparser
    executable: pip3.3
    extra_args: --user

- name: Install shell and extensions
  package:
    name:
      - zsh
      - fonts-powerline
      - fonts-font-awesome
    state: present
    become: yes
  tags:
    - system

- name: check if ZSH exists
  stat:
    path: /usr/bin/zsh
  register: zsh_path
  tags:
    - system

- name: set ZSH as default terminal
  shell: chsh -s $(which zsh)
  when: zsh_path.stat.exists
  tags:
    - system

- name: check if ohmyzsh directory exists
  stat:
    path: "{{ home_directory }}/.oh-my-zsh"
  register: ohmyzsh_directory
  tags:
    - system

- name: clone omyzsh
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "{{ home_directory }}/.oh-my-zsh"
    refspec: "+refs/pull/*:refs/heads/*"
    version: master
  when: not ohmyzsh_directory.stat.exists
  tags:
    - system
