- name: install common packages
  package:
    name:
    - rofi
    - dunst
    - compton
    - powerline
    - fonts-powerline
    - fonts-font-awesome
    state: present
  tags:
    - i3

- name: Install shell
  package:
    name:
      - zsh
    state: present
  tags:
    - system

- name: set ZSH as default terminal
  shell: chsh -s $(which zsh)

- name: clone omyzsh
  shell: git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh