---
- name: Install JDK
  become: yes
  package:
    name:
      - build-essential
      - "openjdk-{{ openjdk_version }}-jdk"
      - "openjdk-{{ openjdk_version }}-doc"
      - "openjdk-{{ openjdk_version }}-jre-headless"
      - "openjdk-{{ openjdk_version }}-source"
    state: present
  tags:
    - development
    - java
    - jdk