- apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install google chrome browser
  package:
    name:
    - google-chrome-stable
    state: present

