- name: Add Google Chrome key
  apt_key:
    url:  https://dl.google.com/linux/linux_signing_key.pub
    state: present
  tags:
    - chrome
    - browser

- name: register google chrome apt repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
  tags:
    - chrome
    - browser

- name: install google chrome browser
  package:
    name: google-chrome-stable
    state: present
  tags:
    - chrome
    - browser

