- name: install common packages
  become: yes
  package:
    name:
    - vim
    - git
    - tig
    - meld
    - diffutils
    - unzip
    - tar
    - coreutils
    - wget
    - python3-pip
    - httpie
    - xfce4-settings
    - chromium-chromedriver
    state: present
  tags:
    - system

- name: Install network tools
  become: yes
  package:
    name:
      - wireshark
      - tcpdump
      - netcat-openbsd
      - iftop
    state: present
  tags:
    - system
