- name: install common packages
  package:
    name:
    - vim
    - git
    - meld
    - diffutils
    - unzip
    - tar
    - coreutils
    state: present
  tags:
    - system

- name: Install network tools
  package:
    name:
      - wireshark
      - tcpdump
      - netcat-openbsd
      - iftop
    state: present
  tags:
    - system
