---
- name: Add Docker GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - container
    - docker

- name: Add Docker APT repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  tags:
    - container
    - docker

- name: Install required system packages
  become: yes
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
    state: present
    update_cache: yes
  tags:
    - container
    - docker

- name: Add user to group 'docker'
  become: yes
  user:
    name: "{{ ansible_user }}"
    group: docker
  tags:
    - container
    - docker

- name: Install docker-compose
  pip:
    name:
      - docker-compose
    executable: pip3
    extra_args: --user